swagger: "2.0"
info:
  title: Demo Service
  description: HTTP service for managing user & their loans
  version: ""
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /loans:
    get:
      tags:
      - loan
      summary: listLoans loan
      description: List all stored loans
      operationId: loan#listLoans
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/LoanLoanResponseTinyCollection'
      schemes:
      - http
  /loans/{id}:
    get:
      tags:
      - loan
      summary: getLoan loan
      description: get loan by ID
      operationId: loan#getLoan
      parameters:
      - name: view
        in: query
        description: View to render
        required: false
        type: string
        default: default
        enum:
        - default
        - tiny
      - name: id
        in: path
        description: ID of loan to show
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/LoanGetLoanResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/LoanGetLoanNotFoundResponseBody'
            required:
            - message
            - id
      schemes:
      - http
  /swagger/swagger.json:
    get:
      tags:
      - swagger
      summary: Download gen/http/openapi.json
      description: JSON document containing the API swagger definition
      operationId: swagger#/swagger/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
  /users:
    get:
      tags:
      - user
      summary: listUsers user
      description: List all stored users
      operationId: user#listUsers
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/UserUserResponseTinyCollection'
      schemes:
      - http
    post:
      tags:
      - user
      summary: createUser user
      description: create new user and return its ID.
      operationId: user#createUser
      parameters:
      - name: CreateUserRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/UserCreateUserRequestBody'
          required:
          - id
          - name
          - email
      responses:
        "201":
          description: Created response.
          schema:
            type: string
      schemes:
      - http
  /users/{id}:
    get:
      tags:
      - user
      summary: getUser user
      description: get user by ID
      operationId: user#getUser
      parameters:
      - name: view
        in: query
        description: View to render
        required: false
        type: string
        enum:
        - default
        - tiny
      - name: id
        in: path
        description: ID of user to show
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/UserGetUserResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/UserGetUserNotFoundResponseBody'
            required:
            - message
            - id
      schemes:
      - http
    delete:
      tags:
      - user
      summary: removeUser user
      description: Remove user
      operationId: user#removeUser
      parameters:
      - name: id
        in: path
        description: ID of user to remove
        required: true
        type: string
      responses:
        "204":
          description: No Content response.
      schemes:
      - http
definitions:
  LoanGetLoanNotFoundResponseBody:
    title: LoanGetLoanNotFoundResponseBody
    type: object
    properties:
      id:
        type: string
        description: ID of missing resource
        example: Et et id ex ducimus architecto voluptatem.
      message:
        type: string
        description: Message of error
        example: user 1 not found
    description: Loan not found
    example:
      id: Nemo est.
      message: user 1 not found
    required:
    - message
    - id
  LoanGetLoanResponseBody:
    title: 'Mediatype identifier: application/vnd.cellar.loan; view=default'
    type: object
    properties:
      amount:
        type: number
        description: Loan amount
        example: 50
        minimum: 50
        maximum: 500
      borrower_id:
        type: integer
        description: id of borrower
        example: 1
        format: int64
      description:
        type: string
        description: description
        example: Impedit non aut.
      id:
        type: integer
        description: ID is the unique id of the loan
        example: 1
        format: int64
      lender_id:
        type: integer
        description: id of lender
        example: 1
        format: int64
      payback_date:
        type: string
        description: Date on which the loan is supposed to be paid back
        example: Illo est nesciunt architecto.
    description: GetLoanResponseBody result type (default view)
    example:
      amount: 50
      borrower_id: 1
      description: Mollitia alias fugiat at.
      id: 1
      lender_id: 1
      payback_date: Animi incidunt.
    required:
    - id
    - amount
    - lender_id
    - borrower_id
  LoanLoanResponseTinyCollection:
    title: 'Mediatype identifier: application/vnd.cellar.loan; type=collection; view=tiny'
    type: array
    items:
      $ref: '#/definitions/LoanResponseTiny'
    description: LoanLoanResponseTinyCollection is the result type for an array of
      LoanResponseTiny (default view)
    example:
    - amount: 50
      borrower_id: 1
      description: Dolores aut minus rem unde quis omnis.
      id: 1
      lender_id: 1
      payback_date: Magnam aperiam.
    - amount: 50
      borrower_id: 1
      description: Dolores aut minus rem unde quis omnis.
      id: 1
      lender_id: 1
      payback_date: Magnam aperiam.
    - amount: 50
      borrower_id: 1
      description: Dolores aut minus rem unde quis omnis.
      id: 1
      lender_id: 1
      payback_date: Magnam aperiam.
    - amount: 50
      borrower_id: 1
      description: Dolores aut minus rem unde quis omnis.
      id: 1
      lender_id: 1
      payback_date: Magnam aperiam.
  LoanResponseTiny:
    title: 'Mediatype identifier: application/vnd.cellar.loan; view=default'
    type: object
    properties:
      amount:
        type: number
        description: Loan amount
        example: 50
        minimum: 50
        maximum: 500
      borrower_id:
        type: integer
        description: id of borrower
        example: 1
        format: int64
      id:
        type: integer
        description: ID is the unique id of the loan
        example: 1
        format: int64
      lender_id:
        type: integer
        description: id of lender
        example: 1
        format: int64
    description: A Loan describes a loan in loan service. (tiny view) (default view)
    example:
      amount: 50
      borrower_id: 1
      id: 1
      lender_id: 1
    required:
    - id
    - amount
    - lender_id
    - borrower_id
  UserCreateUserRequestBody:
    title: UserCreateUserRequestBody
    type: object
    properties:
      email:
        type: string
        description: email address of user
        example: jhon@doe.com
      id:
        type: integer
        description: ID is the unique id of the user.
        example: 1
        format: int64
      name:
        type: string
        description: 'Full Name of the user '
        example: Jesse owens
        minLength: 3
        maxLength: 128
      score:
        type: integer
        description: Score is user's loan score
        example: 100
        minimum: 0
        maximum: 1000
    example:
      email: jhon@doe.com
      id: 1
      name: Jesse owens
      score: 100
    required:
    - id
    - name
    - email
  UserGetUserNotFoundResponseBody:
    title: UserGetUserNotFoundResponseBody
    type: object
    properties:
      id:
        type: string
        description: ID of missing resource
        example: Voluptate qui veniam quia.
      message:
        type: string
        description: Message of error
        example: user 1 not found
    description: User not found
    example:
      id: Esse illo provident.
      message: user 1 not found
    required:
    - message
    - id
  UserGetUserResponseBody:
    title: 'Mediatype identifier: application/vnd.cellar.user; view=default'
    type: object
    properties:
      email:
        type: string
        description: email address of user
        example: jhon@doe.com
      id:
        type: integer
        description: ID is the unique id of the user.
        example: 1
        format: int64
      name:
        type: string
        description: 'Full Name of the user '
        example: Jesse owens
        minLength: 3
        maxLength: 128
      score:
        type: integer
        description: Score is user's loan score
        example: 100
        minimum: 0
        maximum: 1000
    description: GetUserResponseBody result type (default view)
    example:
      email: jhon@doe.com
      id: 1
      name: Jesse owens
      score: 100
    required:
    - id
    - name
    - email
  UserResponseTiny:
    title: 'Mediatype identifier: application/vnd.cellar.user; view=default'
    type: object
    properties:
      id:
        type: integer
        description: ID is the unique id of the user.
        example: 1
        format: int64
      name:
        type: string
        description: 'Full Name of the user '
        example: Jesse owens
        minLength: 3
        maxLength: 128
    description: A User describes a user retrieved by the user service. (tiny view)
      (default view)
    example:
      id: 1
      name: Jesse owens
    required:
    - id
    - name
  UserUserResponseTinyCollection:
    title: 'Mediatype identifier: application/vnd.cellar.user; type=collection; view=tiny'
    type: array
    items:
      $ref: '#/definitions/UserResponseTiny'
    description: UserUserResponseTinyCollection is the result type for an array of
      UserResponseTiny (default view)
    example:
    - email: jhon@doe.com
      id: 1
      name: Jesse owens
      score: 100
    - email: jhon@doe.com
      id: 1
      name: Jesse owens
      score: 100
    - email: jhon@doe.com
      id: 1
      name: Jesse owens
      score: 100
    - email: jhon@doe.com
      id: 1
      name: Jesse owens
      score: 100
